#!/usr/bin/env node
/**
 * update-readme.js
 *
 * Reads the RSS feed from raulcpena.com and rewrites the "Latest from the
 * blog" section of README.md, between these markers:
 *
 *   <!-- BLOG-POST-LIST:START -->
 *   <!-- BLOG-POST-LIST:END -->
 *
 * Run manually:  node scripts/update-readme.js
 * Run in CI:     see .github/workflows/update-readme.yml
 *
 * The feed is generated by src/pages/rss.xml.js in the raulcpena-site repo
 * (@astrojs/rss). It already filters drafts and sorts newest first, so this
 * script just takes the first N items as they come.
 *
 * No dependencies on purpose. The feed is small and Astro's output is
 * predictable: no CDATA, XML entity escaping, one <item> per post.
 */

const FEED_URL = "https://raulcpena.com/rss.xml";
const POST_COUNT = 5;

const START_MARKER = "<!-- BLOG-POST-LIST:START -->";
const END_MARKER = "<!-- BLOG-POST-LIST:END -->";

const ENTITIES = {
  "&apos;": "'",
  "&quot;": '"',
  "&lt;": "<",
  "&gt;": ">",
  "&#39;": "'",
  "&nbsp;": " ",
};

/** Decode the XML entities Astro's RSS output uses. &amp; must go last. */
function decode(s) {
  let out = s;
  for (const [entity, char] of Object.entries(ENTITIES)) {
    out = out.split(entity).join(char);
  }
  return out.split("&amp;").join("&").trim();
}

function tag(block, name) {
  // [^>]* so <guid isPermaLink="true"> style attributes don't break the match
  const m = block.match(new RegExp(`<${name}[^>]*>([\\s\\S]*?)</${name}>`));
  return m ? decode(m[1]) : null;
}

/** Format "Tue, 04 Aug 2026 00:00:00 GMT" as "Aug 4, 2026". */
function formatDate(pubDate) {
  const d = new Date(pubDate);
  if (Number.isNaN(d.valueOf())) return null;
  return d.toLocaleDateString("en-US", {
    timeZone: "UTC",
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}

/** Pure function so it can be tested against a saved feed. */
export function parseFeed(xml) {
  const posts = [];
  const itemRe = /<item>([\s\S]*?)<\/item>/g;
  let match;

  while ((match = itemRe.exec(xml)) !== null) {
    const block = match[1];
    const title = tag(block, "title");
    const link = tag(block, "link");
    const pubDate = tag(block, "pubDate");
    if (!title || !link) continue;
    posts.push({ title, link, date: pubDate ? formatDate(pubDate) : null });
  }

  return posts;
}

function formatList(posts) {
  return posts
    .map((p) => `- [${p.title}](${p.link})${p.date ? ` · ${p.date}` : ""}`)
    .join("\n");
}

async function main() {
  const fs = await import("node:fs/promises");
  const README_PATH = new URL("../README.md", import.meta.url);

  const res = await fetch(FEED_URL, {
    headers: { "User-Agent": "readme-blog-sync-bot" },
  });
  if (!res.ok) throw new Error(`Failed to fetch ${FEED_URL}: ${res.status}`);

  const posts = parseFeed(await res.text()).slice(0, POST_COUNT);
  if (posts.length === 0) {
    console.error("Feed had no items. Leaving README untouched.");
    process.exit(1);
  }

  const readme = await fs.readFile(README_PATH, "utf8");
  const startIdx = readme.indexOf(START_MARKER);
  const endIdx = readme.indexOf(END_MARKER);
  if (startIdx === -1 || endIdx === -1) {
    console.error("Markers not found in README.md. Add them first.");
    process.exit(1);
  }

  const updated =
    readme.slice(0, startIdx + START_MARKER.length) +
    "\n" +
    formatList(posts) +
    "\n" +
    readme.slice(endIdx);

  if (updated === readme) {
    console.log("Blog list already up to date.");
    return;
  }

  await fs.writeFile(README_PATH, updated, "utf8");
  console.log(`Updated README.md with ${posts.length} posts.`);
}

// Only run when executed directly, so tests can import parseFeed.
if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
